### ISSUE TITLE
Suggestion - Auto-detect if default branch is protected + new output "ID of the PR that was created"

### ISSUE THREAD

**Issue by MrChocolatine** [akhilmhdh/contributors-readme-action#37]
1. You should be able to automatically detect if the default branch if protected or not, making the input `is_protected` not needed anymore.

I am suggesting this because I was implementing a reusable workflow for my company, which relies on your GitHub Action, and I wanted to avoid:

1. To manually pass an input `is_protected` from my repositories' workflow to my reusable workflow
2. To pass the `is_protected` from my reusable workflow to your GitHub Action

To me it seemed redundant so I found a way to automate that:

```yaml
jobs:
  update_contributors_list:
    steps:

      - name: Check if the default branch is protected
        id: default_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          defaultBranch="$( \
            gh api /repos/${{ github.repository }} \
              --method GET \
              --jq '.default_branch'
          )"

          isProtected="$( \
            gh api /repos/${{ github.repository }}/branches/$defaultBranch \
              --jq '.protected'
          )"

          echo "::set-output name=is_protected::$isProtected"

      # ...

      - name: Update the list of contributors
        uses: akhilmhdh/contributors-readme-action@v2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_protected: ${{ steps.default_branch.outputs.is_protected == 'true' }}
```

That should be doable directly from your GitHub Action.

2. The second suggestion directly follows the first one. If the default branch is indeed protected and your GitHub Action had to create a PR, it would be nice to have the ID of that newly created PR as an output.
