### ISSUE TITLE
Automated Branch Protection Detection

### ISSUE THREAD

**Issue by paulmowat** [akhilmhdh/contributors-readme-action#43]
Hi,

Just started using this and wanted to use this along with branch protection.

I noticed a recent change to automate detection of this and to raise a PR instead of doing it automatically.

It is possible to have branch protection and set up appropriate personal access tokens that you could pass instead of the GITHUB_TOKEN to allow it to work.

I have this working on v2.3 with a branch setup with branch protection and the is_protected option set to false (to avoid PR creation) and it updates fine.

```yaml
jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3
        env:
            GITHUB_TOKEN: ${{ secrets.BUILD_SVC_PAT }}
        with:
          is_protected: false
          commit_message: contrib-readme-action has updated readme [skip ci]
```

It would be good to still have ability to set is_protected to override the automated logic for above scenario.

Thanks

Paul
