### ISSUE TITLE
Does it always create a PR or only when the contribution section needs to change?

### ISSUE THREAD

**Issue by praveenpuglia** [akhilmhdh/contributors-readme-action#64]
Here's the workflow that I am using
```yml
on:
  push:
    branches:
      - development

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The first time I tried it, it created the contributor section and all worked well but on the subsequent PRs, even after they are merged to development, I get nothing.

The job runs successfully though.

<img width="836" alt="image" src="https://github.com/akhilmhdh/contributors-readme-action/assets/313363/594868e0-596b-4b3e-bbff-4e022333e4be">

I was wondering if it only creates a PR if there's a change in the contribution list in that case?
