### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by Stoppedwumm** [akhilmhdh/contributors-readme-action#70]
I followed the tutorial and got this error:

Error: Resource not accessible by integration
<img width="982" alt="Bildschirmfoto 2024-02-22 um 15 45 09" src="https://github.com/akhilmhdh/contributors-readme-action/assets/129097720/ce25a8ff-cb85-476a-8244-0b04cbca6a31">

```yml
on:
    push:
        branches:
            - main

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
