### ISSUE TITLE
[FEATURE] Update multiple files at once

### ISSUE THREAD

**Issue by guibranco** [akhilmhdh/contributors-readme-action#79]
I want to request the option to update multiple files simultaneously instead of running the same action twice (or more) and creating N pull requests instead of just one.

For example, in my project, I show the contributors in two places: the main README.md file and another `.md` file in the `/docs` directory. When I run this action, I need to run it in a single workflow but with 2 separate steps, which always generate two pull requests (check suites, builds, and validations for each one). 

I would like to pass an array of files, and this action changes all the files in one round, even with multiple commits, but all in a single pull request.

This is the `steps` section of my current `YAML` file:

```yml
steps:
  - name: Contribute List in README.md
    uses: akhilmhdh/contributors-readme-action@v2.3.10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      readme_path: README.md

  - name: Contribute List in README.md
    uses: akhilmhdh/contributors-readme-action@v2.3.10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      readme_path: docs/contributing.md
```
